function reportcopied = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   REPORTCOPIED = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   REPORTCOPIED = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   reportcopied = importfile('report_copied.csv', 2, 1486);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/07/29 08:08:53

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: categorical (%C)
%	column6: double (%f)
%   column7: categorical (%C)
%	column8: double (%f)
%   column9: categorical (%C)
%	column10: double (%f)
%   column11: categorical (%C)
%	column12: double (%f)
%   column13: categorical (%C)
%	column14: double (%f)
%   column15: categorical (%C)
%	column16: double (%f)
%   column17: categorical (%C)
%	column18: double (%f)
%   column19: categorical (%C)
%	column20: double (%f)
%   column21: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
reportcopied = table(dataArray{1:end-1}, 'VariableNames', {'V','E','sccs','boost','boostCorrected','tarjan_map','tarjan_mapCorrected','nuutila1_map','nuutila1_mapCorrected','nuutila1_iterative','nuutila1_iterativeCorrected','nuutila2_map','nuutila2_mapCorrected','nuutila2_iterative','nuutila2_iterativeCorrected','pearce1_map','pearce1_mapCorrected','pearce2_map','pearce2_mapCorrected','pearce2_iterative','pearce2_iterativeCorrected'});

