# Inspired by https://github.com/boostorg/hana/blob/master/.travis.yml

language: cpp
sudo: false

# default job
# GCC 7
os: linux
dist: trusty
env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

matrix:
  include:

    # Xcode Clang
    - os: osx
      osx_image: xcode9
      env: MATRIX_EVAL=""

    # Clang 5.0
    - os: linux
      dist: trusty
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons: &defaults { apt: { packages: ["clang-5.0"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"] } }

    # Clang 6.0
    - os: linux
      dist: trusty
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      addons: &defaults { apt: { packages: ["clang-6.0"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-6.0"] } }

    # GCC 6
    - os: linux
      dist: trusty
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - (mkdir build && cd build && cmake -DSCC_ALGORITHM_BUILD_TEST=ON ..)

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - (cd build && make && ./libsccalgorithms/test/SCCAlgorithms_test)
